package bupt.ugrd.controller;

/**
 * Created by Luyao on 2018/1/20.
 */

import bupt.ugrd.dao.GoldBugDao;
import bupt.ugrd.model.*;
import bupt.ugrd.pojo.*;
import bupt.ugrd.util.Constants;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


@RestController
@RequestMapping("/goldbug")
public class GoldBugController {

    // This means to get the bean called userinfoRepositor which is auto-generated by Spring, we will use it to handle the data
    @Autowired
    private ContentRepository contentRepository;

    @Autowired
    private BuginfoRepository buginfoRepository;

    @Autowired
    private Buginfo2Repository buginfo2Repository;

    @Autowired
    private DebugrecordRepository debugrecordRepository;

    @Autowired
    private Userinfo2Repository userinfo2Repository;

    @Autowired
    private GoldBugDao goldBugDaoImp;


    @RequestMapping("getAroundBugs")
    public @ResponseBody List<BugBasic> getAroundBugs(@RequestBody Coordinate userTmp){

        List<BugBasic> bugList = goldBugDaoImp.getAroungBugs(userTmp.getLon(), userTmp.getLat(), userTmp.getUserId());
        return bugList;

    }

    @RequestMapping("/getSpecBug")
    public @ResponseBody BugSpecOne getSpecBug(@RequestBody  Common common){
        int bid = common.getBid();
        int userId = common.getUserId();


        int arIndex = 0;
        int lifecount = 0;

        BugSpecOne bugSpecOne = new BugSpecOne();

        bugSpecOne.setSuccess(false);


        int type = common.getType();

        if(type == 1){ // 已经成功回答过
            bugSpecOne.setDes("已经成功回答过啦");
            return bugSpecOne;
        }
        if(type == 2){ // 未回答过 && 距离太远
            bugSpecOne.setDes("距离虫子再近点才能答题哦");
            return bugSpecOne;
        }
        else { // type 为1 开始进入答题  ||  superuser

            Buginfo2 bug = goldBugDaoImp.getBuginfo2ByBugId(bid);
            if(bug != null){
                //double lon = bug.getLon();
                //double lat = bug.getLat();

                //double userLon = common.getRt_lon();
                //double userLat = common.getRt_lat();

                // double distTmp = Math.pow(bug.getLon()-common.getRt_lon(), 2)+Math.pow(bug.getLat()-common.getRt_lat(), 2);
                if(common.getIsSuperUser() == 0){
                    arIndex = bug.getArIndex();
                    lifecount = bug.getLifecount();
                }
                else {

                   // if(Math.abs(lat - userLat) > Constants.MIN_LAT_DISTANCE && Math.abs(lon - userLon) > Constants.MIN_LON_DISTANCE) {
                    //    bugSpecOne.setDes("距离虫子再近点才能答题哦");
                     //   return bugSpecOne;
                   // }
                   // else {
                        arIndex = bug.getArIndex();
                        lifecount = bug.getLifecount();
                   // }
                }

            }
            else {  // 找不到该虫子
                bugSpecOne.setSuccess(false);
                return bugSpecOne;
            }

            /*
            if(common.getIsSuperUser() != 0){
                Debugrecord debugrecord = goldBugDaoImp.getDebugRecord(bid, userId);
                if(debugrecord!=null && debugrecord.getState() == 0){
                    bugSpecOne.setSuccess(false);
                    bugSpecOne.setDes("已经成功回答过啦");
                    return bugSpecOne;
                }
            }*/

            bugSpecOne.setArIndex(arIndex);
            bugSpecOne.setLifecount(lifecount);


            bupt.ugrd.model.Content content_ = contentRepository.findOne(bid);
            List<String> answers = new ArrayList<String>();
            answers.add(content_.getAns_1());
            answers.add(content_.getAns_2());
            answers.add(content_.getAns_3());
            answers.add(content_.getAns_4());
            bugSpecOne.setAnswer(answers);
            bugSpecOne.setBugId(bid);
            bugSpecOne.setQuestion(content_.getQuestion());
            bugSpecOne.setSuccess(true);
            bugSpecOne.setScore(content_.getScore());
            bugSpecOne.setKey_(content_.getKey_());

            return bugSpecOne;
        }


    }


    @RequestMapping("/vaildBug")
    public @ResponseBody Result vaildBug(@RequestBody  Common common ){
        Debugrecord record = new Debugrecord();
        int userId = common.getUserId();
        double userScore = 0;

        String choose = common.getChoose();
        Result result = new Result();
        int state = 1;

        int bid = common.getBugId();
        boolean res = false;


        Buginfo2 buginfo2 = goldBugDaoImp.getBuginfo2ByBugId(bid);

        if(buginfo2 != null){

            if(buginfo2.getStatus() == 1){
                return new Result(false, "虫子还未到活跃时间点哦", 1, false, null);
            }
            else if(buginfo2.getStatus() == 0) {
                record.setBugId(bid);
                record.setUserId(common.getUserId());
                record.setDebugDate(common.getDebugDate());

                bupt.ugrd.model.Content content_ = contentRepository.findOne(bid);
                if(content_.getKey_().equals(choose)){
                    res = true;
                }

                if(res){
                    Userinfo2 userTmp = userinfo2Repository.findOne(userId);
                    userScore = userTmp.getScore();

                    int lifecount = buginfo2.getLifecount();
                    if(lifecount == 1){
                        buginfo2.setLifecount(0);
                        buginfo2.setStatus(2);
                        state = 0;

                        userScore += content_.getScore();
                        userTmp.setScore(userScore);
                        userinfo2Repository.save(userTmp);
                    }
                    else if(lifecount > 1){
                        lifecount-=1;
                        buginfo2.setLifecount(lifecount);
                        state = 0;

                        userScore += content_.getScore();
                        userTmp.setScore(userScore);
                        userinfo2Repository.save(userTmp);
                    }
                    else {
                        state = 1;
                        buginfo2.setStatus(-2);
                    }

                    Buginfo buginfo = buginfoRepository.findOne(buginfo2.getId());
                    buginfo2.setBugId(buginfo);
                    buginfo2Repository.save(buginfo2);

                    record.setState(state);
                    record.setChoice(choose);
                    debugrecordRepository.save(record);

                    return new Result(true, "恭喜回答正确", 0, false, null);
                }
                else{
                    state = 1;
                    record.setState(state);
                    record.setChoice(choose);
                    debugrecordRepository.save(record);

                    return new Result(false, "回答错误，再想想哦", 1, false, null);
                }


            }
            else {
                return new Result(false, "捉虫失败", 1, false, null);
            }
        }

        return new Result(false, "虫子不存在哦", 1, false, null);
    }


    @RequestMapping("addGoldBug") //@RequestBody BugInfo bugInfo, @RequestBody Content content
    public @ResponseBody Result addNewGoldbug(@RequestBody BugContent bugContent){

        BugInfo bugInfo = bugContent.getBugInfo();
        bupt.ugrd.pojo.Content content = bugContent.getContent();


        Buginfo bug = new Buginfo();
        bug.setDeathTime(bugInfo.getDeathTime());
        bug.setStartTime(bugInfo.getStartTime());
        bug.setStart_lat(bugInfo.getStart_lat());
        bug.setStart_lon(bugInfo.getStart_lon());
        bug.setEnd_lat(bugInfo.getEnd_lat());
        bug.setEnd_lon(bugInfo.getEnd_lon());
        bug.setIfNeedStartTime(bugInfo.isIfNeedStartTime());
        bug.setIsMoved(bugInfo.isMoved());
        bug.setLifecount(bugInfo.getLifecount());
        bug.setPlanter(bugInfo.getPlanter());
        buginfoRepository.save(bug);



        Buginfo2 buginfo2 = new Buginfo2();
        buginfo2.setBugId(bug);
        buginfo2.setLifecount(bugInfo.getLifecount());
        buginfo2.setStatus(-1);
        buginfo2.setResOfCheck(-1);
        buginfo2.setArIndex(content.getArIndex());
        buginfo2Repository.save(buginfo2);
        System.out.println("This New BUG is Connecting with  Bug "+buginfo2.getBugId().getId()+"in the Table BugInfo~~~~~~~~~`");



        bupt.ugrd.model.Content cont = new bupt.ugrd.model.Content();
        cont.setBugId(bug.getId());
        cont.setDescription(content.getDescription());
        cont.setQuestion(content.getQuestion());
        cont.setScore(content.getScore());
        cont.setAns_1(content.getAns_1());
        cont.setAns_2(content.getAns_2());
        cont.setAns_3(content.getAns_3());
        cont.setAns_4(content.getAns_4());
        cont.setContentType(content.getContentType());
        cont.setKey_(content.getKey_());
        contentRepository.save(cont);

        return new Result(true, "sucess", 0, false, null);

    }

}
