package bupt.ugrd.controller;

/**
 * Created by Luyao on 2018/1/20.
 */

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import bupt.ugrd.pojo.Bug;
import bupt.ugrd.pojo.BugRepository;


@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called bugRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private BugRepository bugRepository;

    @GetMapping(path="/add") // Map ONLY GET Requests
    public @ResponseBody String addNewUser (@RequestParam String planter) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Bug n = new Bug();
        n.setPlanter(planter);
        bugRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Bug> getAllUsers() {
        // This returns a JSON or XML with the users
        return bugRepository.findAll();
    }
}
