package bupt.ugrd.controller;

import bupt.ugrd.model.Userinfo;
import bupt.ugrd.model.Userinfo2;
import bupt.ugrd.model.Userinfo2Repository;
import bupt.ugrd.model.UserinfoRepository;
import bupt.ugrd.pojo.Result;
import bupt.ugrd.pojo.User;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import java.util.Iterator;

/**
 * Created by Luyao on 2018/4/26.
 */

@RestController
@RequestMapping("/user")
public class UserController {
    @Autowired
    // This means to get the bean called userinfoRepositor which is auto-generated by Spring, we will use it to handle the data
    private UserinfoRepository userinfoRepository;

    @Autowired
    private Userinfo2Repository userinfo2Repository;

    @RequestMapping("addUser")
    public @ResponseBody Result addNewUser(@RequestBody User user){
        if(this.findUserByName(user.getUserName()) == null){
            Userinfo newUser = new Userinfo(user.getUserPhone(), user.getUserName(), user.getCreateTime());
            userinfoRepository.save(newUser);

            Userinfo2 userinfo2 = new Userinfo2();
            userinfo2.setUserId(newUser.getId());
            userinfo2Repository.save(userinfo2);

            return new Result(true, "success", 0);
        }
        return new Result(false, "User Name Already Existed!", 1);

    }

    public Userinfo findUserByName(String userName) {
        Iterable<Userinfo> users = userinfoRepository.findAll();
        Iterator<Userinfo> it= users.iterator();

        while(it.hasNext()){
            Userinfo user = it.next();
            if(user.getUserName().equals(userName)){
                return user;
            }
        }
        return null;
    }


}
